
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1


spring.cloud.gateway.routes[1].id=driver-service
spring.cloud.gateway.routes[1].uri=lb://DRIVER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/driver-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1


spring.cloud.gateway.routes[2].id=ride-service
spring.cloud.gateway.routes[2].uri=lb://RIDE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/ride-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
